[custom]
; Clash 基础全局配置
mixed-port=7890
allow-lan=true
bind-address=*
mode=rule
log-level=info
external-controller=127.0.0.1:9090

; Hosts 解析
hosts[]=auto.server-refresh.com:106.75.133.181

; DNS配置
dns_enable=true
dns_ipv6=false
dns_listen=0.0.0.0:1053
dns_enhanced_mode=fake-ip
dns_fake_ip_range=198.18.0.1/16
dns_use_hosts=true
dns_respect_rules=false

; 1. 默认与基础解析服务
default_nameserver[]=223.5.5.5
default_nameserver[]=119.29.29.29

; 2. 主解析服务 (nameserver)
nameserver[]=223.5.5.5
nameserver[]=119.29.29.29
nameserver[]=https://doh.pub/dns-query
nameserver[]=https://dns.alidns.com/dns-query

; 3. 条件解析策略 (nameserver-policy)
nameserver_policy[]=mirrors.nd-fs-lucky-3.com:https://auto.server-refresh.com:27772/dns-query/fixedtoken

; 4. 海外及回退解析 (fallback & fallback-filter)
fallback[]=8.8.8.8
fallback[]=1.1.1.1
fallback[]=https://doh.dns.sb/dns-query
fallback[]=https://dns.cloudflare.com/dns-query
fallback[]=https://dns.twnic.tw/dns-query
fallback[]=tls://8.8.4.4:853

fallback_filter_geoip=true
fallback_filter_ipcidr[]=240.0.0.0/4
fallback_filter_ipcidr[]=0.0.0.0/32

; 规则集定义
ruleset=🤖 AI,https://raw.githubusercontent.com/gavinkhaos/Rule/main/AI_Rule.list
ruleset=🐸 手动切换,[]MATCH

; 策略组定义
custom_proxy_group=🤖 AI`select`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🐸 手动切换
custom_proxy_group=🐸 手动切换`select`.*
custom_proxy_group=🇯🇵 日本节点`select`(日本)
custom_proxy_group=🇺🇸 美国节点`select`(美国)
custom_proxy_group=🇸🇬 新加坡节点`select`(新加坡)

; 启用自定义规则生成
enable_rule_generator=true
overwrite_original_rules=true
